config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create, :show]
  
  get '/session/admin_preview/:id', to: 'sessions#admin_preview'
  get '/session/admin_switchback',  to: 'sessions#admin_switchback'

  resource  :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
    resources :movies, only: [:new, :create]
  end

  root to: 'movies#index'

end

app/controllers/admin/movies_controller.rb
require 'open-uri'

class Admin::MoviesController < ApplicationController

  before_action :verify_admin

  def new
    @movie = Movie.new
  end

  def create
    movie_hash = Movie.load_omdb(movie_params)
    if movie_hash.blank?
      @movie = Movie.new
      @movie.errors[:base] << "Failed to load from OMDB!"
      render :new
      return
    end

    @movie = Movie.create(movie_hash)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was loaded from OMDB."
    else
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:imdb_id, :title)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :restrict_access, except: [:index, :show]

  def index
    @movies = search.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
    @movie = Movie.find(params[:id].to_i)
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id].to_i)
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted."
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id].to_i)

    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id].to_i)
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image, :remote_poster_image_url, :description
    )
  end

  def search
    Movie.query_name(params[:q_name]).query_runtime_from(params[:q_runtime_from]).query_runtime_to(params[:q_runtime_to])
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
    <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @movie do |f| %>
  <div class="input-group">
    <%= f.label "title" %><br />
    <%= f.text_field "title" %>
  </div>
  <div class="input-group">
    <%= f.label "release_date" %><br />
    <%= f.date_field "release_date" %>
  </div>
  <div class="input-group">
    <%= f.label "director" %><br />
    <%= f.text_field "director" %>
  </div>
  <div class="input-group">
    <%= f.label "runtime_in_minutes" %><br />
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div class="input-group">
    <%= f.label :poster_image %><br />
    <%= f.file_field :poster_image %><br />
    &nbsp;&nbsp; <%= f.label :remote_poster_image_url, "or image URL:" %><br />
    &nbsp;&nbsp; <%= f.text_field :remote_poster_image_url %>
  </div>
  <div class="input-group">
    <%= f.label "description" %><br />
    <%= f.text_area "description" %>
  </div>
  <div class="input-group">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="list-group-item">
  <%= link_to image_tag(movie.poster_image_url(:thumb).to_s), movie_path(movie) %>
  <h3>
    <%= link_to movie.title, movie_path(movie) %>
  </h3>
  <h4>
    <%= format_date(movie.release_date) %>
  </h4>
  <h5 class="movie_detail">
    Directed by: <%= movie.director %> ||
    Running Time: <%= movie.runtime_in_minutes %> minutes
  </h5>
  <p>
    <%= movie.description %>
  </p>
</div>

app/views/movies/_review.html.erb
<h3>
  Reviews
</h3>
<% if current_user %>
  <h4>
    Average Rating: <%= @movie.review_average %> 
  </h4>

  <div class="list-group">
    <% @movie.reviews.each do |review| %>
      <div class="list-group-item">
        <p> <%= review.text %> </p>
        <p> <%= review.rating_out_of_ten %>/10 </p>
        <small> 
          by: <%= link_to review.user.full_name, user_path(review.user) %> 
        </small>
      </div>
      <br />
    <% end %>
  </div>

  <%= link_to "Write your review!", new_movie_review_path(@movie), class: "new_edit" %>
<% else %>
  <p class="ask_login">
    <%= link_to "Log in", new_session_path %> to see reviews and add your own.
  </p>
<% end %>

app/views/movies/_search.html.erb
<h3>Search Movies</h3>

<%= form_tag(movies_path, method: "get") do %>
  <%= label_tag(:q_name, "By Title or Director: ") %>
  <%= text_field_tag(:q_name) %>
  <hr />
  <%= label_tag(:q_runtime_from, "By Running Time: ") %>
  <%= number_field_tag(:q_runtime_from, nil, in: 1..200, size: 4) %>
  <%= label_tag(:q_runtime_to, " minutes to ") %>
  <%= number_field_tag(:q_runtime_to, nil, in: 1..200, size: 4) %> minutes
  <hr />
  <%= submit_tag("Search") %> | <%= button_tag("Reset", type: "reset") %>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Show Movie", movie_path(@movie), class: "new_edit" %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<% if current_user %>
  <%= link_to "Submit a new movie!", new_movie_path, class: "new_edit" %>
  <hr />
<% else %>
  <p class="ask_login">
    <%= link_to "Log in", new_session_path %> to submit new movies!
  </p>
<% end %>

<div class="search_box">
  <%= render "search" %>
</div>

<hr />
<%= paginate @movies %>

<div class="list-group">
  <% @movies.each do |movie| %>
    <%= render partial: "movie", object: movie %>
    <br />
  <% end %>
</div>

app/views/movies/new.html.erb
<%= link_to "All Movies", movies_path,  class: "new_edit" %>

<h2>Submit a new movie!</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "All Movies", movies_path, class: "new_edit" %>
<hr />
<%= link_to image_tag(@movie.poster_image_url.to_s), movie_path(@movie) %>
<h2>
  <%= @movie.title %>
</h2>
<h4>
  <%= format_date(@movie.release_date) %>
</h4>
<h4> 
  Director: <%= @movie.director %> <br />
  Running Time: <%= @movie.runtime_in_minutes %> minutes
</h4>
<p>
  <%= @movie.description %>
</p>

<hr />

<% if current_user %>
  <%= link_to "edit movie", edit_movie_path(@movie), class: "new_edit" %>
  &nbsp;&nbsp;
  <%= link_to "delete movie", movie_path(@movie), method: :delete, 
      data: { confirm: "Are you sure you want to delete this movie?" },
      class: "new_edit" %>
<% else %>
  <p class="ask_login">
    <%= link_to "Log in", new_session_path %> to edit or delete this movie.
  </p>
<% end %>

<hr />

<%= render 'review' %>