config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create, :show]
  
  get '/session/admin_preview/:id', to: 'sessions#admin_preview'
  get '/session/admin_switchback',  to: 'sessions#admin_switchback'

  resource  :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
    resources :movies, only: [:new, :create]
  end

  root to: 'movies#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :reviews, dependent: :destroy

  validates :email, presence: true,
                    uniqueness: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create
  validates :admin, inclusion: { in: [true, false] }

  scope :query_name,  -> (q_name)     {
    q_name.blank? ? all : where("(firstname like ?) OR (lastname like ?)", "%#{q_name}%", "%#{q_name}%")
  }

  scope :query_email, -> (q_email)     {
    q_email.blank? ? all : where("email like ?", "%#{q_email}%")
  }

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :verify_admin

  def index
    @admin_users = search.order(created_at: :asc).page(params[:page]).per(10)
  end

  def new
    @admin_user = User.new
  end

  def create
    @admin_user = User.new(user_params)

    if @admin_user.save
      redirect_to admin_user_path(@admin_user), notice: "#{@admin_user.full_name} was created."
    else
      render :new
    end
  end

  def show
    @admin_user = User.find(params[:id].to_i)
  end

  def edit
    @admin_user = User.find(params[:id].to_i)
  end

  def update
    @admin_user = User.find(params[:id].to_i)

    if @admin_user.update(user_params)
      redirect_to admin_user_path(@admin_user), notice: "#{@admin_user.full_name} was updated."
    else
      render :edit
    end
  end

  def destroy
    @admin_user = User.find(params[:id].to_i)
    UserMailer.delete_user_email(@admin_user).deliver
    @admin_user.destroy

    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

  def search
    User.query_name(params[:q_name]).query_email(params[:q_email])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin = false

    if @user.save
      # auto login
      session[:user_id] = @user.id 
      redirect_to movies_path, notice: "Welcome, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @profile_user = User.find(params[:id].to_i)
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @admin_user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <%= pluralize(@admin_user.errors.count, "error") %> prevented this user from being submitted:
    <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([:admin, @admin_user]) do |f| %>
  <div class="input-group">
    <%= f.label "firstname" %><br />
    <%= f.text_field "firstname" %>
  </div>
  <div class="input-group">
    <%= f.label "lastname" %><br />
    <%= f.text_field "lastname" %>
  </div>
  <div class="input-group">
    <%= f.label "email" %><br />
    <%= f.text_field "email" %>
  </div>
  <div class="input-group">
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div class="input-group">
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div class="input-group">
    <%= f.label "admin", "Is this user an admin?" %> &nbsp;
    <%= f.check_box "admin" %>
  </div>
  <div class="input-group">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Show User", admin_user_path(@admin_user), class: "new_edit" %>

<h3>Edit this user</h3>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<%= render 'admin/dashboard' %>

<h3>List of Users</h3>

<div class="search_box">
  <%= render "admin/search" %>
</div>

<%= paginate @admin_users %>
<br />

<table class="table">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Preview As</th>
    </tr>
  </thead>
  <tbody>
    <% @admin_users.each do |user| %>
      <tr>
        <td>
          <h4>
            <%= link_to user.full_name, admin_user_path(user) %>
          </h4>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= link_to "Preview", "/session/admin_preview/#{user.id}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= render 'admin/dashboard' %>

<h3>Create a new user</h3>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= link_to "All Users", admin_users_path, class: "new_edit" %>
<hr />

<h3>
  <%= @admin_user.full_name %>
</h3>
<h4>
  <%= @admin_user.email %>
</h4>
<p> 
  Created at <%= format_date(@admin_user.created_at) %> <br />
  Last updated at <%= format_date(@admin_user.updated_at) %>
</p>
<hr />

<%= link_to "Edit user", edit_admin_user_path(@admin_user), class: "new_edit" %> 
&nbsp;
<%= link_to "Delete user", admin_user_path(@admin_user), method: :delete, 
    data: { confirm: "Are you sure you want to delete this user?" }, 
    class: "new_edit" %>