config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create, :show]
  
  get '/session/admin_preview/:id', to: 'sessions#admin_preview'
  get '/session/admin_switchback',  to: 'sessions#admin_switchback'

  resource  :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
    resources :movies, only: [:new, :create]
  end

  root to: 'movies#index'

end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      You are signed in as: <%= current_user.full_name %> (<%= link_to "Log Out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>

    <% if preview_mode? %>
      <p>
        You are in preview mode. <%= link_to "Switch back to admin", "/session/admin_switchback" %>?
      </p>
    <% elsif is_admin? %>
      <p>
        <%= link_to "Admin Dashboard", admin_users_path %>
      </p>
    <% end %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="jumbotron">
  <h1>Rotten Mangoes</h1>
  <p>
    This Rotten Tomatoes clone allows users to submit movies and review them. It is a learning project for web development on Rails. Please don't take it seriously.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-warning", role: "alert") if key == 'alert' %>
      <%= content_tag(:div, value, class: "alert alert-success", role: "alert") if key == 'notice' %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>